#!/usr/bin/env bash
set -e

# Define actions and tags to track
actions=(
  "actions/checkout@v4"
  "pnpm/action-setup@v2"
  "actions/setup-node@v4"
  "changesets/action@v1"
)

output_file=".github/action-pinned-commits.yaml"

echo "# This file is auto-generated by .github/update-action-pins.sh" > "$output_file"
echo "pins:" >> "$output_file"

for action in "${actions[@]}"; do
  repo="${action%@*}"
  tag="${action#*@}"
  
  echo "Fetching latest commit for $repo @ $tag..."
  
  # Fetch the commit hash using git ls-remote
  # Handles both tags (refs/tags/v1) and branches if applicable, but usually tags for actions
  commit_hash=$(git ls-remote "https://github.com/$repo.git" "refs/tags/$tag" | awk '{print $1}' | head -n 1)
  
  # Fallback: try fetching the tag directly if refs/tags/ prefix fails (some actions strictly use semantic versioning without v prefix or other quirks)
  if [ -z "$commit_hash" ]; then
      commit_hash=$(git ls-remote "https://github.com/$repo.git" "$tag" | awk '{print $1}' | head -n 1)
  fi

  if [ -z "$commit_hash" ]; then
    echo "Error: Could not find commit hash for $repo@$tag"
    exit 1
  fi
  
  echo "  \"$action\": \"$commit_hash\"" >> "$output_file"
done

echo "Updated $output_file"
