#!/usr/bin/env bash
set -e

# Define actions and tags to track
actions=(
  "actions/checkout@v4"
  "pnpm/action-setup@v2"
  "actions/setup-node@v4"
  "actions/github-script@v7"
  "googleapis/release-please-action@v4"
  "actions/create-github-app-token@v1"
)

output_file=".github/action-pinned-commits.yaml"

echo "# This file is auto-generated by .github/update-action-pins.sh" > "$output_file"
echo "pins:" >> "$output_file"

for action in "${actions[@]}"; do
  repo="${action%@*}"
  tag="${action#*@}"
  
  echo "Processing $repo @ $tag..."
  
  # Fetch the commit hash for the requested tag (e.g., v4)
  # For annotated tags, we want the peeled commit hash (ending in ^{}), not the tag object hash.
  refs=$(git ls-remote "https://github.com/$repo.git" "refs/tags/$tag")
  commit_hash=$(echo "$refs" | grep '\^{}$' | awk '{print $1}')
  
  if [ -z "$commit_hash" ]; then
    commit_hash=$(echo "$refs" | awk '{print $1}' | head -n 1)
  fi
  
  if [ -z "$commit_hash" ]; then
      # Fallback for non-v prefix or branch names
      commit_hash=$(git ls-remote "https://github.com/$repo.git" "$tag" | awk '{print $1}' | head -n 1)
  fi

  if [ -z "$commit_hash" ]; then
    echo "Error: Could not find commit hash for $repo@$tag"
    exit 1
  fi
  
  # Resolve the specific version tag for this commit
  # 1. List all tags pointing to this commit
  # 2. Filter for tags starting with v (or simple numbers)
  # 3. Sort by version (sort -V) and take the last one to get the latest/most specific
  resolved_version=$(git ls-remote --tags "https://github.com/$repo.git" | grep "$commit_hash" | awk '{print $2}' | sed 's|refs/tags/||' | grep -v '\^{}' | sort -V | tail -n 1)
  
  if [ -z "$resolved_version" ]; then
      resolved_version="$tag" # Fallback to input tag if no specific tag found
  fi

  echo "  --> Resolved to $commit_hash ($resolved_version)"

  echo "  \"$action\":" >> "$output_file"
  echo "    commit: \"$commit_hash\"" >> "$output_file"
  echo "    version: \"$resolved_version\"" >> "$output_file"
done

echo "Updated $output_file"
