name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0 # Needed for coverage diff
          filter: blob:none

      - name: Project Setup
        uses: ./.github/actions/setup

      - name: Build and Quality Check
        run: pnpm build-ci

      - name: Run Tests with Coverage on Changed Files
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          pnpm vitest run --passWithNoTests --coverage --changed ${{ github.base_ref }}
